# SPDX-License-Identifier: MIT

from enum import IntEnum


class SessionState(IntEnum):
    PEER_DISCOVERY = 0,
    SESSION_INITIALISATION = 1,
    IN_SESSION = 2,
    SESSION_TERMINATION = 3,
    SESSION_RESET = 4


class SignalType(IntEnum):
    RESERVED = 0,
    PEER_DISCOVERY_SIGNAL = 1,
    PEER_OFFER_SIGNAL = 2


class MessageType(IntEnum):
    RESERVED = 0,
    SESSION_INITIALISATION_MESSAGE = 1,
    SESSION_INITIALISATION_RESPONSE_MESSAGE = 2,
    SESSION_UPDATE_MESSAGE = 3,
    SESSION_UPDATE_RESPONSE_MESSAGE = 4,
    SESSION_TERMINATION_MESSAGE = 5,
    SESSION_TERMINATION_RESPONSE_MESSAGE = 6,
    DESTINATION_UP_MESSAGE = 7,
    DESTINATION_UP_RESPONSE_MESSAGE = 8,
    DESTINATION_ANNOUNCE_MESSAGE = 9,
    DESTINATION_ANNOUNCE_RESPONSE_MESSAGE = 10,
    DESTINATION_DOWN_MESSAGE = 11,
    DESTINATION_DOWN_RESPONSE_MESSAGE = 12,
    DESTINATION_UPDATE_MESSAGE = 13,
    LINK_CHARACTERISTICS_REQUEST_MESSAGE = 14,
    LINK_CHARACTERISTICS_RESPONSE_MESSAGE = 15,
    HEARTBEAT_MESSAGE = 16


class DataItemType(IntEnum):
    STATUS = 1,
    IPV4_CONNECTION_POINT = 2,
    IPV6_CONNECTION_POINT = 3,
    PEER_TYPE = 4,
    HEARTBEAT_INTERVAL = 5,
    EXTENSIONS_SUPPORTED = 6,
    MAC_ADDRESS = 7,
    IPV4_ADDRESS = 8,
    IPV6_ADDRESS = 9,
    IPV4_ATTACHED_SUBNET = 10,
    IPV6_ATTACHED_SUBNET = 11,
    MAXIMUM_DATA_RATE_RX = 12,
    MAXIMUM_DATA_RATE_TX = 13,
    CURRENT_DATA_RATE_RX = 14,
    CURRENT_DATA_RATE_TX = 15,
    LATENCY = 16,
    RESOURCES = 17,
    RELATIVE_LINK_QUALITY_RX = 18,
    RELATIVE_LINK_QUALITY_TX = 19,
    MAXIMUM_TRANSMISSION_UNIT = 20,
    LOSS_RATE = 65408


class StatusCode(IntEnum):
    SUCCESS = 0,
    NOT_INTERESTED = 1,
    REQUEST_DENIED = 2,
    INCONSISTENT_DATA = 3,
    UNKNOWN_MESSAGE = 128,
    UNEXPECTED_MESSAGE = 129,
    INVALID_DATA = 130,
    INVALID_DESTINATION = 131,
    TIMED_OUT = 132,
    SHUTTING_DOWN = 255

